---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    app.openshift.io/connects-to: '[{"apiVersion":"kubevirt.io/v1","kind":"VirtualMachine","name":"winweb02"},{"apiVersion":"kubevirt.io/v1","kind":"VirtualMachine","name":"winweb01"}]'
  labels:
    app: database
    app.kubernetes.io/part-of: 3-Tier-App
  name: database
  namespace: user1-{{ .Values.windows_mesh_namespace }}
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: database
    spec:
      source:
        http:
          url: {{ .Values.vms_image_url }}/database.qcow2
      storage:
        resources:
          requests:
            storage: 16Gi
  running: {{ .Values.vms_start_vms }}
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: centos9
        vm.kubevirt.io/workload: server
        sidecar.istio.io/inject: "true"
      labels:
        sidecar.istio.io/inject: "true"
        kubevirt.io/domain: database
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            bios: {}
        machine:
          type: {{ .Values.vms_machine_type }}
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: database
        name: rootdisk
