{{- if eq .Values.ocp4_workload_virt_roadshow_multi_user_network_roles_configure "true" -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-nodenetworkconfigurationresources
rules:
  - apiGroups:
      - nmstate.io
    resources:
      - nodenetworkconfigurationenactments
      - nodenetworkconfigurationpolicies
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-nodenetworkstates
rules:
  - apiGroups:
      - nmstate.io
    resources:
      - nodenetworkstates
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: network-attachment-admin
rules:
  - apiGroups:
      - "k8s.cni.cncf.io"
    resources:
      - network-attachment-definitions
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: network-attachment-admin-binding
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:authenticated'
roleRef:
  kind: ClusterRole
  name: network-attachment-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-nodenetworkconfigurationresources-binding
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:authenticated'
roleRef:
  kind: ClusterRole
  name: list-nodenetworkconfigurationresources
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-nodenetworkstates-binding
  namespace: default
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:authenticated'
roleRef:
  kind: ClusterRole
  name: list-nodenetworkstates
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
