kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: database
  namespace: user{{ .Values.user_number }}-{{ .Values.windows_mesh_namespace_base }}
  labels:
    kiali_wizard: request_routing
spec:
  hosts:
    - database.user{{ .Values.user_number }}-{{ .Values.windows_mesh_namespace_base }}.svc.cluster.local
  http:
    - route:
        - destination:
            host: database.user{{ .Values.user_number }}-{{ .Values.windows_mesh_namespace_base }}.svc.cluster.local
          weight: 100
