---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: route-job
  namespace: user{{ .Values.user_number }}-{{ .Values.windows_mesh_namespace_base }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: route-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: route-job
  namespace: user{{ .Values.user_number }}-{{ .Values.windows_mesh_namespace_base }}
---
# templates/gateway-patch.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: user{{ .Values.user_number }}-gateway-patch
  namespace: user{{ .Values.user_number }}-{{ .Values.windows_mesh_namespace_base }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: route-job
      containers:
      - name: gateway-patch
        image: quay.io/agnosticd/ee-multicloud:v0.1.2
        command:
        - /bin/sh
        - -c
        - |
          ROUTE_HOST=$(oc get route user{{ .Values.user_number }} -n istio-system -o jsonpath='{.spec.host}')
          echo $ROUTE_HOST

          oc patch gateway winmesh-gateway -n user{{ .Values.user_number }}-{{ .Values.windows_mesh_namespace_base }} \
            --type=json -p "[{\"op\": \"replace\", \"path\": \"/spec/servers/0/hosts\", \"value\": [\"$ROUTE_HOST\"]}]"
          oc patch virtualservice winmesh -n user{{ .Values.user_number }}-{{ .Values.windows_mesh_namespace_base }} \
            --type=json -p "[{\"op\": \"replace\", \"path\": \"/spec/hosts\", \"value\": [\"$ROUTE_HOST\"]}]"
      restartPolicy: Never
