---
apiVersion: v1
kind: Service
metadata:
  name: winmesh
  namespace: user1-{{ .Values.windows_mesh_namespace }}
spec:
  selector:
    env: winmesh
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
