---
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: basic
  namespace: {{ .Values.istio_cp_namespace }}
spec:
  version: v2.6
  addons:
    grafana:
      enabled: true
    kiali:
      enabled: true
    prometheus:
      enabled: true
  gateways:
    openshiftRoute:
      enabled: false
  policy:
    type: Istiod
  profiles:
    - default
  security:
    controlPlane:
      mtls: true
    dataPlane:
      mtls: true
{{- if eq .Values.cloud "rosa" }}
    identity:
      type: ThirdParty
{{- end }}
  telemetry:
    type: Istiod
  tracing:
    type: None
  runtime:
    components:
      pilot:
        deployment:
          replicas: 3
        pod:
          affinity: {}
        container:
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
      grafana:
        deployment: {}
        pod: {}
      kiali:
        deployment: {}
        pod: {}
