---
apiVersion: v1
kind: ConfigMap
metadata:
  name: userinfo
  namespace: {{ .Values.istio_cp_namespace }}
  labels:
    demo.redhat.com/userinfo: ""
data:
  hairball: companion
  users_json: >-
    {"users": {
          {{- range $i := untilStep 1 ( .Values.user.count | add1 | int ) 1 -}}
          {{- if ne $i 1 -}},{{- end -}}
    "user{{ $i }}": { "kiali_url": "https://kiali-{{$.Values.istio_cp_namespace}}.{{ $.Values.deployer.domain }}", "happy": "news" }
        {{- end -}} }}
