---
apiVersion: v1
kind: ConfigMap
metadata:
  name: userinfo-users-json
  namespace: {{ .Values.istio_cp_namespace }}
  labels:
    demo.redhat.com/userinfo: ""
data:
  first: userinfo-users-json
  users_json: >-
    {"users": {
          {{- range $i := untilStep 1 ( .Values.user.count | add1 | int ) 1 -}}
          {{- if ne $i 1 -}},{{- end -}}
    "user{{ $i }}": { "kiali_url": "https://kiali-{{$.Values.istio_cp_namespace}}.{{ $.Values.deployer.domain }}", "first": "json" }
        {{- end -}} }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: userinfo-users-json2
  namespace: {{ .Values.istio_cp_namespace }}
  labels:
    demo.redhat.com/userinfo: ""
data:
  second: userinfo-users-json2
  hairball: companion
  users_json: >-
    {"users": {
          {{- range $i := untilStep 1 ( .Values.user.count | add1 | int ) 1 -}}
          {{- if ne $i 1 -}},{{- end -}}
    "user{{ $i }}": {  "second": "json" }
        {{- end -}} }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: userinfo-yaml
  namespace: {{ .Values.istio_cp_namespace }}
  labels:
    demo.redhat.com/userinfo: ""
data:
  third: userinfo-yaml
  user_data: base
  user_data_one: one
  user_data_two: two
