---
apiVersion: v1
kind: Service
metadata:
  name: winmesh
  namespace: user{{ .Values.user_number }}-{{ .Values.windows_mesh_namespace_base }}
spec:
  selector:
    env: winmesh
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
