---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: database
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
spec:
  source:
    http:
      url: {{ $.Values.vms_image_url }}/database.qcow2
  storage:
    resources:
      requests:
        storage: 16Gi
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: database-volumesnapshot
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  volumeSnapshotClassName: ocs-storagecluster-rbdplugin-snapclass
  source:
    persistentVolumeClaimName: database
