---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: database
  namespace: default
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
spec:
  source:
    http:
      url: {{ $.Values.vms_image_url }}/database.qcow2
  storage:
    resources:
      requests:
        storage: 16Gi
