---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: winweb03
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
spec:
  source:
    http:
      url: {{ $.Values.vms_image_url }}/winweb02.qcow2
  storage:
    resources:
      requests:
        storage: 90Gi
