---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: winweb01
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
spec:
  source:
    http:
      url: {{ $.Values.vms_image_url }}/winweb01.qcow2
  storage:
    resources:
      requests:
        storage: 90Gi
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
  annotations:
    argocd.argoproj.io/sync-wave: "2"
metadata:
  name: winweb01-volumesnapshot
  namespace: default
spec:
  volumeSnapshotClassName: ocs-storagecluster-rbdplugin-snapclass
  source:
    persistentVolumeClaimName: winweb01
