---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: {{ .Values.windows_mesh_namespace }}
spec:
  selector:
    vm.kubevirt.io/name: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
